# docker-compose.yml
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"   # host:container (changed from 5000:8081)
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"       # host:container
    restart: always

